Don't push duplicates.

diff --git a/.github/workflows/test-issuer-frontend-docker.yml b/.github/workflows/test-issuer-frontend-docker.yml
--- a/.github/workflows/test-issuer-frontend-docker.yml
+++ b/.github/workflows/test-issuer-frontend-docker.yml
@@ -31,7 +31,18 @@ jobs:
           password: ${{ secrets.DOCKERHUB_TOKEN }}
       - name: Extract tag from package.json
         id: meta
-        run: echo "version=$(jq -r .version test-tools/issuer-front-end/package.json)" > "$GITHUB_OUTPUT"
+        run: |
+          export VERSION=$(jq -r .version test-tools/issuer-front-end/package.json)
+          export FULL_IMAGE_TAG="${{ env.REGISTRY }}/concordium/$IMAGE_NAME:$VERSION"
+          echo "::notice FULL_IMAGE_TAG=${FULL_IMAGE_TAG}"
+          # Make sure the image does not exist. Abort if we can retrieve any metadata.
+          if docker manifest inspect docker.io/concordium/issuer-front-end:1.0.14 > /dev/null; then
+             echo "::error ${FULL_IMAGE_TAG} already exists"
+             exit 1
+          else
+             # Store the full image tag into a tag variable for the following step.
+             echo "tag=${FULL_IMAGE_TAG}" > "$GITHUB_OUTPUT"
+          fi
       - name: Build and push Docker image
         uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
         with:
@@ -39,4 +50,4 @@ jobs:
           file: ./test-tools/issuer-front-end/Dockerfile
           push: true
           platforms: linux/amd64
-          tags: ${{ env.REGISTRY }}/concordium/${{ env.IMAGE_NAME}}:${{ steps.meta.outputs.version }}
+          tags: ${{ steps.meta.outputs.tag }}
